# Generated by Django 3.0.3 on 2020-02-08 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0002_auto_20200208_1850'),
    ]

    operations = [
        migrations.CreateModel(
            name='housing_type',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('housing_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Household',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('album_name', models.CharField(max_length=100)),
                ('artist', models.CharField(max_length=100)),
                ('housing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='household.housing_type')),
            ],
        ),
        migrations.AlterField(
            model_name='track',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='household.Household'),
        ),
        migrations.DeleteModel(
            name='Album',
        ),
    ]
