# Generated by Django 3.0.3 on 2020-02-08 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0003_auto_20200208_1857'),
    ]

    operations = [
        migrations.RenameField(
            model_name='track',
            old_name='album',
            new_name='householdID',
        ),
        migrations.RemoveField(
            model_name='household',
            name='album_name',
        ),
        migrations.RemoveField(
            model_name='household',
            name='artist',
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('householdID', 'order')},
        ),
    ]
