# Generated by Django 3.0.3 on 2020-02-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0004_auto_20200208_1911'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='track',
            options={'ordering': ['name']},
        ),
        migrations.RenameField(
            model_name='track',
            old_name='title',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='track',
            name='householdID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_member', to='household.Household'),
        ),
        migrations.AlterUniqueTogether(
            name='track',
            unique_together={('householdID', 'name')},
        ),
        migrations.RemoveField(
            model_name='track',
            name='duration',
        ),
        migrations.RemoveField(
            model_name='track',
            name='order',
        ),
    ]
