# Generated by Django 3.0.3 on 2020-02-08 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0005_auto_20200208_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='track',
            name='householdID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='household.Household'),
        ),
    ]
