# Generated by Django 3.0.3 on 2020-02-08 11:43

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0007_auto_20200208_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_individual',
            name='DOB',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='annual_income',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='gender',
            field=models.IntegerField(choices=[(1, 'Male'), (2, 'Female')], default=1),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='marital_status',
            field=models.IntegerField(choices=[(1, 'Single'), (2, 'Married'), (3, 'Widowed'), (4, 'Separated'), (5, 'Divorced'), (6, 'Not reported')], default=1),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='occupation_type',
            field=models.IntegerField(choices=[(1, 'Unemployed'), (2, 'Student'), (3, 'Employed')], default=1),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='spouse',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='household.household_individual'),
        ),
    ]
