# Generated by Django 3.0.3 on 2020-02-08 11:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0008_auto_20200208_1943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_individual',
            name='householdID',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='family_members', to='household.Household'),
        ),
    ]
