# Generated by Django 3.0.3 on 2020-02-09 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0010_auto_20200208_2244'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household_individual',
            name='spouse',
            field=models.CharField(max_length=100),
        ),
    ]
