# Generated by Django 3.0.3 on 2020-02-10 01:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0012_auto_20200210_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='household_individual',
            name='spouse',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
