# Generated by Django 3.0.3 on 2020-02-10 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('household', '0013_auto_20200210_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='household',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
